use_frameworks!

platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'WiseTrackLib_Example' do
  pod 'WiseTrackLib', :path => '../', :testspecs => ['UITests', 'UnitTests']
end
